SET search_path TO public;

CREATE TABLE IF NOT EXISTS gateway_sql_resource_usage (
  id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_log_id         BIGINT NOT NULL,
  request_id             VARCHAR(64) NOT NULL,
  tenant_code            VARCHAR(64) NOT NULL,
  dataset_id             VARCHAR(64) NOT NULL,
  create_time            TIMESTAMP(3) NOT NULL,
  execute_time           TIMESTAMP(3) NULL,
  execute_status         VARCHAR(20) NOT NULL,

  sql_template           TEXT NOT NULL,
  sql_resolved           TEXT NOT NULL,
  analyzed_at            TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  planning_time_ms       DOUBLE PRECISION,
  execution_time_ms      DOUBLE PRECISION,
  cpu_time_ms            DOUBLE PRECISION,

  rows                   BIGINT,
  costs                  DOUBLE PRECISION,
  plan_rows              BIGINT,
  plan_width             INTEGER,

  shared_hit_blocks      BIGINT,
  shared_read_blocks     BIGINT,
  shared_dirtied_blocks  BIGINT,
  shared_written_blocks  BIGINT,
  local_hit_blocks       BIGINT,
  local_read_blocks      BIGINT,
  local_dirtied_blocks   BIGINT,
  local_written_blocks   BIGINT,
  temp_read_blocks       BIGINT,
  temp_written_blocks    BIGINT,

  io_read_bytes          BIGINT,
  io_write_bytes         BIGINT,
  io_total_bytes         BIGINT,

  peak_memory_kb         DOUBLE PRECISION,
  memory_estimated_kb    DOUBLE PRECISION,

  error_message          TEXT,
  plan_json              JSONB,

  CONSTRAINT uq_gateway_sql_resource_usage_request_log_id UNIQUE (request_log_id),
  CONSTRAINT fk_gateway_sql_resource_usage_request_log
    FOREIGN KEY (request_log_id)
    REFERENCES gateway_sql_request_log(id)
    ON DELETE CASCADE,
  CONSTRAINT chk_gateway_sql_resource_usage_status
    CHECK (execute_status IN ('INIT','SUCCESS','FAILED','TIMEOUT'))
);

CREATE INDEX IF NOT EXISTS idx_gateway_sql_resource_usage_request_id
  ON gateway_sql_resource_usage (request_id);

CREATE INDEX IF NOT EXISTS idx_gateway_sql_resource_usage_tenant_create_time
  ON gateway_sql_resource_usage (tenant_code, create_time);

CREATE INDEX IF NOT EXISTS idx_gateway_sql_resource_usage_dataset_create_time
  ON gateway_sql_resource_usage (dataset_id, create_time);

CREATE INDEX IF NOT EXISTS idx_gateway_sql_resource_usage_status_analyzed
  ON gateway_sql_resource_usage (execute_status, analyzed_at);

COMMENT ON TABLE gateway_sql_resource_usage IS 'Gateway SQL资源消耗明细表（按请求SQL逐条采集）';
COMMENT ON COLUMN gateway_sql_resource_usage.request_log_id IS '关联 gateway_sql_request_log.id';
COMMENT ON COLUMN gateway_sql_resource_usage.request_id IS '请求ID；同一个外部请求可对应多条SQL';
COMMENT ON COLUMN gateway_sql_resource_usage.tenant_code IS '租户编码';
COMMENT ON COLUMN gateway_sql_resource_usage.dataset_id IS '数据集ID';
COMMENT ON COLUMN gateway_sql_resource_usage.create_time IS '请求创建时间/进入网关时间';
COMMENT ON COLUMN gateway_sql_resource_usage.execute_time IS '执行完成时间';
COMMENT ON COLUMN gateway_sql_resource_usage.execute_status IS '执行状态：INIT/SUCCESS/FAILED/TIMEOUT';
COMMENT ON COLUMN gateway_sql_resource_usage.sql_template IS '原始模板SQL（可能含 {tenant_code} 变量）';
COMMENT ON COLUMN gateway_sql_resource_usage.sql_resolved IS '变量替换后的可执行SQL';
COMMENT ON COLUMN gateway_sql_resource_usage.planning_time_ms IS 'EXPLAIN ANALYZE 规划耗时(ms)';
COMMENT ON COLUMN gateway_sql_resource_usage.execution_time_ms IS 'EXPLAIN ANALYZE 执行耗时(ms)';
COMMENT ON COLUMN gateway_sql_resource_usage.cpu_time_ms IS 'CPU耗时估算(ms)，当前采用执行时长近似';
COMMENT ON COLUMN gateway_sql_resource_usage.rows IS '实际返回行数(Actual Rows)';
COMMENT ON COLUMN gateway_sql_resource_usage.costs IS '优化器总代价(Total Cost)';
COMMENT ON COLUMN gateway_sql_resource_usage.plan_rows IS '预估行数(Plan Rows)';
COMMENT ON COLUMN gateway_sql_resource_usage.plan_width IS '预估行宽(Plan Width)';
COMMENT ON COLUMN gateway_sql_resource_usage.io_read_bytes IS '读取IO字节数估算(块数*8KB)';
COMMENT ON COLUMN gateway_sql_resource_usage.io_write_bytes IS '写入IO字节数估算(块数*8KB)';
COMMENT ON COLUMN gateway_sql_resource_usage.io_total_bytes IS '总IO字节数估算';
COMMENT ON COLUMN gateway_sql_resource_usage.peak_memory_kb IS '峰值内存(KB)，优先取计划节点 Peak Memory Usage';
COMMENT ON COLUMN gateway_sql_resource_usage.memory_estimated_kb IS '内存估算(KB)，基于 rows*plan_width';
COMMENT ON COLUMN gateway_sql_resource_usage.error_message IS '采集失败原因';
COMMENT ON COLUMN gateway_sql_resource_usage.plan_json IS '完整 EXPLAIN JSON，便于追溯';
