SET search_path TO public;

CREATE TABLE IF NOT EXISTS gateway_sql_request_log (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_id     VARCHAR(64) NOT NULL,
  tenant_code    VARCHAR(64) NOT NULL,
  dataset_id     VARCHAR(64) NOT NULL,
  sql_content    TEXT NOT NULL,
  create_time    TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  execute_time   TIMESTAMP(3) NULL,
  execute_status VARCHAR(20) NOT NULL DEFAULT 'INIT',
  CONSTRAINT chk_gateway_sql_request_log_status
    CHECK (execute_status IN ('INIT','SUCCESS','FAILED','TIMEOUT'))
);

CREATE INDEX IF NOT EXISTS idx_request_id
  ON gateway_sql_request_log (request_id);

CREATE INDEX IF NOT EXISTS idx_tenant_create_time
  ON gateway_sql_request_log (tenant_code, create_time);

CREATE INDEX IF NOT EXISTS idx_dataset_create_time
  ON gateway_sql_request_log (dataset_id, create_time);

CREATE INDEX IF NOT EXISTS idx_status_create_time
  ON gateway_sql_request_log (execute_status, create_time);

COMMENT ON TABLE gateway_sql_request_log IS 'Gateway SQL请求日志表';
COMMENT ON COLUMN gateway_sql_request_log.id IS '主键ID';
COMMENT ON COLUMN gateway_sql_request_log.request_id IS '请求ID；同一个外部请求可对应多条SQL';
COMMENT ON COLUMN gateway_sql_request_log.tenant_code IS '租户编码';
COMMENT ON COLUMN gateway_sql_request_log.dataset_id IS '数据集ID';
COMMENT ON COLUMN gateway_sql_request_log.sql_content IS '查询SQL内容（可包含 {tenant_code} 变量）';
COMMENT ON COLUMN gateway_sql_request_log.create_time IS '请求创建时间/进入网关时间';
COMMENT ON COLUMN gateway_sql_request_log.execute_time IS '执行完成时间';
COMMENT ON COLUMN gateway_sql_request_log.execute_status IS '执行状态：INIT/SUCCESS/FAILED/TIMEOUT';
